{% set name = "langchain-core" %}
{% set version = "0.2.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_core-{{ version }}.tar.gz
  sha256: 20c7792eb6c256dc50892d41f07f7fd8e12e5868dbb059fa316a278977bdf4f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - pydantic >=1,<3
    - langsmith >=0.1.75,<0.2.0
    - tenacity >=8.1.0,!=8.4.0,<9.0.0
    - jsonpatch >=1.33.0,<2.0.0
    - pyyaml >=5.3
    - packaging >=23.2.0,<25.0.0
  run_constrained:
    - jinja2 >=3.0.0,<4.0.0

test:
  imports:
    - langchain_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://api.python.langchain.com/en/stable/core_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/core
  summary: Core APIs for LangChain, the LLM framework for buildilng applications through composability
  description: LangChain Core contains the core abstractions powering LangChain, including LangChain Expression Language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - pavelzw
